name: Build macOS App

on:
  push:
    branches: [ main ]  # 或者你自己的分支
  workflow_dispatch:    # 允许你手动触发

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  # 或者你项目使用的版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build macOS App
      run: |
        pyinstaller --onefile --windowed --name="demo" --icon=mainpic.icns \
          --add-data "*.png:." --add-data "*.webp:." --add-data "*.mp3:." mainpet.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: demo-mac
        path: dist/demo
